---
title: "RandomForest multiclasifiación"
author: "Alejandro Bedoya Cataño"
date: "30/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Carga de librerías

```{r message=FALSE, warning=FALSE}
library(caret)
library(randomForest)
set.seed(123)
```

# Lectura de las bases de datos

```{r}
setwd("C:/Users/123/Desktop/TAE/Actividades/TRABAJO 1")
train <- read.csv("train.csv", header = TRUE)
test <- read.csv("test.csv", header = TRUE)
train <- train[,-c(1)]
test <- test[,-c(1)]
```

# Conversión de variables a factor

```{r}
train$Hijos <- factor(train$Hijos)
train$nivel_edu <- as.factor(train$nivel_edu)
train$estu_actual <- as.factor(train$estu_actual)
train$tipo_trabajo <- as.factor(train$tipo_trabajo)
train$estado_civil <- as.factor(train$estado_civil)
train$sexo <- as.factor(train$sexo)
train$conyugue_hogar <- as.factor(train$conyugue_hogar)

summary(train)
```


# Contrucción del modelo

```{r}
names(train)
bosque <- train(Hijos ~ CANT_PERSONAS_HOGAR+conyugue_hogar+edad_conyugue+
                 edad_jefe+sexo  
                ,data = train, method = 'rf', 
                trControl = trainControl(method='cv',number = 5))
```


```{r}
bosque
```

